// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI5IuqnQNWvK75yrv1rXLde7He7iXdZCc',
    appId: '1:294318775511:web:b0eb2d1e8582f561e6a492',
    messagingSenderId: '294318775511',
    projectId: 'adet-ka-ching',
    authDomain: 'adet-ka-ching.firebaseapp.com',
    storageBucket: 'adet-ka-ching.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEussjr9Woev07sQHzwV2PU8n67S1rPNY',
    appId: '1:294318775511:android:df9bd46a21807346e6a492',
    messagingSenderId: '294318775511',
    projectId: 'adet-ka-ching',
    storageBucket: 'adet-ka-ching.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxtrxUTLInD99tKjRNklcPA2YJZQ2UuxY',
    appId: '1:294318775511:ios:be567fadbfdf90b8e6a492',
    messagingSenderId: '294318775511',
    projectId: 'adet-ka-ching',
    storageBucket: 'adet-ka-ching.firebasestorage.app',
    iosBundleId: 'com.example.adetKaChing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxtrxUTLInD99tKjRNklcPA2YJZQ2UuxY',
    appId: '1:294318775511:ios:be567fadbfdf90b8e6a492',
    messagingSenderId: '294318775511',
    projectId: 'adet-ka-ching',
    storageBucket: 'adet-ka-ching.firebasestorage.app',
    iosBundleId: 'com.example.adetKaChing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI5IuqnQNWvK75yrv1rXLde7He7iXdZCc',
    appId: '1:294318775511:web:44acd5aeec6c6f33e6a492',
    messagingSenderId: '294318775511',
    projectId: 'adet-ka-ching',
    authDomain: 'adet-ka-ching.firebaseapp.com',
    storageBucket: 'adet-ka-ching.firebasestorage.app',
  );
}
